#!/bin/bash
# tabix 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

  echo "tabix started on $(date)"

  echo "Value of in_vcf:         '${in_vcf}'"
  echo "Value of out_filename:   '${out_filename}'"

  dx download "${in_vcf}" -o in_vcf.gz
  tabix -p vcf in_vcf.gz

  out_tbi=$(dx upload in_vcf.gz.tbi --destination ${out_filename} --brief)
  dx-jobutil-add-output out_tbi "${out_tbi}" --class=file

  echo "tabix finished on $(date)"
}
