#!/bin/bash
# cat-files 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

  echo "cat-files started on $(date)"

  echo "Value of files: '${file[@]}'"
  echo "Value of out_filename: '${out_filename}'"

  >out_file
  for i in ${!file[@]}
  do
    dx cat "${file[$i]}" >> out_file
  done

  out_file=$(dx upload out_file --destination ${out_filename} --brief)
  dx-jobutil-add-output out_file "${out_file}" --class=file

  echo "cat-files finished on $(date)"
}
