#!/bin/bash
# Beagle 5.4
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of mem:  '${mem}'"
    echo "Value of gt:   '${gt}'"
    echo "Value of map:  '${map}'"
    echo "Value of out:  '${out}'"
    echo "Value of args: '${args}'"

    dx download "${gt}"  -o gt.vcf.gz
    dx download "${map}" -o gen.map

    java -ea -Xmx${mem} -jar beagle.22Jul22.46e.jar gt=gt.vcf.gz map=gen.map out=${out} ${args}

    out_vcf=$(dx upload ${out}.vcf.gz --brief)
    log=$(dx upload ${out}.log --brief)

    dx-jobutil-add-output out_vcf "${out_vcf}" --class=file
    dx-jobutil-add-output log "${log}" --class=file
}
